### ISSUE TITLE
`initialize': unknown option: {:options=>#<Selenium::WebDriver::Firefox::Options:0x000000010b8dc0 @args=[], @binary=nil, @profile=nil, @log_level=nil, @prefs={}, @options={}>} (ArgumentError)

### ISSUE THREAD

**Issue by VeeanB** [watir/ww_note#2]
Hi,
Can any one help me for this issue,
while running script i am getting this kind of error .please help me

**Comment by p0deje** [comment]
This is not a repository anybody looks at. See https://github.com/watir/watir.
